config/routes.rb
Blazer::Engine.routes.draw do
  resources :queries do
    post :run, on: :collection # err on the side of caution
    post :cancel, on: :collection
    post :refresh, on: :member
    get :tables, on: :collection
    get :schema, on: :collection
    get :docs, on: :collection
  end

  resources :checks, except: [:show] do
    get :run, on: :member
  end

  resources :dashboards, except: [:index] do
    post :refresh, on: :member
  end

  if Blazer.uploads?
    resources :uploads do
    end
  end

  root to: "queries#home"
end

app/models/blazer/audit.rb
module Blazer
  class Audit < Record
    belongs_to :user, optional: true, class_name: Blazer.user_class.to_s
    belongs_to :query, optional: true
  end
end

app/models/blazer/connection.rb
module Blazer
  class Connection < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/blazer/dashboard.rb
module Blazer
  class Dashboard < Record
    belongs_to :creator, optional: true, class_name: Blazer.user_class.to_s if Blazer.user_class
    has_many :dashboard_queries, dependent: :destroy
    has_many :queries, through: :dashboard_queries

    validates :name, presence: true

    def variables
      queries.flat_map { |q| q.variables }.uniq
    end

    def to_param
      [id, name.gsub("'", "").parameterize].join("-")
    end
  end
end

app/models/blazer/dashboard_query.rb
module Blazer
  class DashboardQuery < Record
    belongs_to :dashboard
    belongs_to :query

    validates :dashboard_id, presence: true
    validates :query_id, presence: true
  end
end

app/models/blazer/query.rb
module Blazer
  class Query < Record
    belongs_to :creator, optional: true, class_name: Blazer.user_class.to_s if Blazer.user_class
    has_many :checks, dependent: :destroy
    has_many :dashboard_queries, dependent: :destroy
    has_many :dashboards, through: :dashboard_queries
    has_many :audits

    validates :statement, presence: true

    scope :active, -> { column_names.include?("status") ? where(status: ["active", nil]) : all }
    scope :named, -> { where.not(name: "") }

    def to_param
      [id, name].compact.join("-").gsub("'", "").parameterize
    end

    def friendly_name
      name.to_s.sub(/\A[#\*]/, "").gsub(/\[.+\]/, "").strip
    end

    def editable?(user)
      !persisted? || (name.present? && name.first != "*" && name.first != "#") || user == try(:creator)
    end

    def variables
      # don't require data_source to be loaded
      variables = Statement.new(statement).variables
      variables += ["cohort_period"] if cohort_analysis?
      variables
    end

    def cohort_analysis?
      # don't require data_source to be loaded
      Statement.new(statement).cohort_analysis?
    end

    def statement_object
      Statement.new(statement, data_source)
    end
  end
end

app/controllers/blazer/base_controller.rb
module Blazer
  class BaseController < ApplicationController
    # skip filters
    filters = _process_action_callbacks.map(&:filter) - [:activate_authlogic]
    skip_before_action(*filters, raise: false)
    skip_after_action(*filters, raise: false)
    skip_around_action(*filters, raise: false)

    clear_helpers

    protect_from_forgery with: :exception

    if ENV["BLAZER_PASSWORD"]
      http_basic_authenticate_with name: ENV["BLAZER_USERNAME"], password: ENV["BLAZER_PASSWORD"]
    end

    if Blazer.settings["before_action"]
      raise Blazer::Error, "The docs for protecting Blazer with a custom before_action had an incorrect example from August 2017 to June 2018. The example method had a boolean return value. However, you must render or redirect if a user is unauthorized rather than return a falsy value. Double check that your before_action works correctly for unauthorized users (if it worked when added, there should be no issue). Then, change before_action to before_action_method in config/blazer.yml."
    end

    if Blazer.before_action
      before_action Blazer.before_action.to_sym
    end

    if Blazer.override_csp
      after_action do
        response.headers['Content-Security-Policy'] = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval' data: blob:"
      end
    end

    layout "blazer/application"

    private

    def process_vars(statement, var_params = nil)
      var_params ||= request.query_parameters
      (@bind_vars ||= []).concat(statement.variables).uniq!
      # update in-place so populated in view and consistent across queries on dashboard
      @bind_vars.each do |var|
        if !var_params[var]
          default = statement.data_source.variable_defaults[var]
          # only add if default exists
          var_params[var] = default if default
        end
      end
      runnable = @bind_vars.all? { |v| var_params[v] }
      statement.add_values(var_params) if runnable
      runnable
    end

    def refresh_query(query)
      statement = query.statement_object
      runnable = process_vars(statement)
      cohort_analysis_statement(statement) if statement.cohort_analysis?
      statement.clear_cache if runnable
    end

    def add_cohort_analysis_vars
      @bind_vars << "cohort_period" unless @bind_vars.include?("cohort_period")
      @smart_vars["cohort_period"] = ["day", "week", "month"] if @smart_vars
      # TODO create var_params method
      request.query_parameters["cohort_period"] ||= "week"
    end

    def parse_smart_variables(var, data_source)
      smart_var_data_source =
        ([data_source] + Array(data_source.settings["inherit_smart_settings"]).map { |ds| Blazer.data_sources[ds] }).find { |ds| ds.smart_variables[var] }

      if smart_var_data_source
        query = smart_var_data_source.smart_variables[var]

        if query.is_a? Hash
          smart_var = query.map { |k,v| [v, k] }
        elsif query.is_a? Array
          smart_var = query.map { |v| [v, v] }
        elsif query
          result = smart_var_data_source.run_statement(query)
          smart_var = result.rows.map { |v| v.reverse }
          error = result.error if result.error
        end
      end

      [smart_var, error]
    end

    def cohort_analysis_statement(statement)
      @cohort_period = params["cohort_period"] || "week"
      @cohort_period = "week" unless ["day", "week", "month"].include?(@cohort_period)

      # for now
      @conversion_period = @cohort_period
      @cohort_days =
        case @cohort_period
        when "day"
          1
        when "week"
          7
        when "month"
          30
        end

      statement.apply_cohort_analysis(period: @cohort_period, days: @cohort_days)
    end

    def variable_params(resource, var_params = nil)
      permitted_keys = resource.variables
      var_params ||= request.query_parameters
      var_params.slice(*permitted_keys)
    end
    helper_method :variable_params

    def nested_variable_params(resource)
      variable_params(resource, request.query_parameters["variables"] || {})
    end
    helper_method :nested_variable_params

    def blazer_user
      send(Blazer.user_method) if Blazer.user_method && respond_to?(Blazer.user_method, true)
    end
    helper_method :blazer_user

    def render_errors(resource)
      @errors = resource.errors
      action = resource.persisted? ? :edit : :new
      render action, status: :unprocessable_entity
    end

    # do not inherit from ApplicationController - #120
    def default_url_options
      {}
    end
  end
end

app/controllers/blazer/checks_controller.rb
module Blazer
  class ChecksController < BaseController
    before_action :set_check, only: [:edit, :update, :destroy, :run]

    def index
      state_order = [nil, "disabled", "error", "timed out", "failing", "passing"]
      @checks = Blazer::Check.joins(:query).includes(:query).order("blazer_queries.name, blazer_checks.id").to_a.sort_by { |q| state_order.index(q.state) || 99 }
      @checks.select! { |c| "#{c.query.name} #{c.emails}".downcase.include?(params[:q]) } if params[:q]
    end

    def new
      @check = Blazer::Check.new(query_id: params[:query_id])
    end

    def create
      @check = Blazer::Check.new(check_params)
      # use creator_id instead of creator
      # since we setup association without checking if column exists
      @check.creator = blazer_user if @check.respond_to?(:creator_id=) && blazer_user

      if @check.save
        redirect_to query_path(@check.query)
      else
        render_errors @check
      end
    end

    def update
      if @check.update(check_params)
        redirect_to query_path(@check.query)
      else
        render_errors @check
      end
    end

    def destroy
      @check.destroy
      redirect_to checks_path
    end

    def run
      @query = @check.query
      redirect_to query_path(@query)
    end

    private

    def check_params
      params.require(:check).permit(:query_id, :emails, :slack_channels, :invert, :check_type, :schedule)
    end

    def set_check
      @check = Blazer::Check.find(params[:id])
    end
  end
end

app/controllers/blazer/dashboards_controller.rb
module Blazer
  class DashboardsController < BaseController
    before_action :set_dashboard, only: [:show, :edit, :update, :destroy, :refresh]

    def new
      @dashboard = Blazer::Dashboard.new
    end

    def create
      @dashboard = Blazer::Dashboard.new
      # use creator_id instead of creator
      # since we setup association without checking if column exists
      @dashboard.creator = blazer_user if @dashboard.respond_to?(:creator_id=) && blazer_user

      if update_dashboard(@dashboard)
        redirect_to dashboard_path(@dashboard)
      else
        render_errors @dashboard
      end
    end

    def show
      @queries = @dashboard.dashboard_queries.order(:position).preload(:query).map(&:query)
      @queries.each do |query|
        @success = process_vars(query.statement_object)
      end
      @bind_vars ||= []

      @smart_vars = {}
      @sql_errors = []
      @data_sources = @queries.map { |q| Blazer.data_sources[q.data_source] }.uniq
      @bind_vars.each do |var|
        @data_sources.each do |data_source|
          smart_var, error = parse_smart_variables(var, data_source)
          ((@smart_vars[var] ||= []).concat(smart_var)).uniq! if smart_var
          @sql_errors << error if error
        end
      end

      add_cohort_analysis_vars if @queries.any?(&:cohort_analysis?)
    end

    def edit
    end

    def update
      if update_dashboard(@dashboard)
        redirect_to dashboard_path(@dashboard, params: variable_params(@dashboard))
      else
        render_errors @dashboard
      end
    end

    def destroy
      @dashboard.destroy
      redirect_to root_path
    end

    def refresh
      @dashboard.queries.each do |query|
        refresh_query(query)
      end
      redirect_to dashboard_path(@dashboard, params: variable_params(@dashboard))
    end

    private

    def dashboard_params
      params.require(:dashboard).permit(:name)
    end

    def set_dashboard
      @dashboard = Blazer::Dashboard.find(params[:id])
    end

    def update_dashboard(dashboard)
      dashboard.assign_attributes(dashboard_params)
      Blazer::Dashboard.transaction do
        if params[:query_ids].is_a?(Array)
          query_ids = params[:query_ids].map(&:to_i)
          @queries = Blazer::Query.find(query_ids).sort_by { |q| query_ids.index(q.id) }
        end
        if dashboard.save
          if @queries
            @queries.each_with_index do |query, i|
              dashboard_query = dashboard.dashboard_queries.where(query_id: query.id).first_or_initialize
              dashboard_query.position = i
              dashboard_query.save!
            end
            if dashboard.persisted?
              dashboard.dashboard_queries.where.not(query_id: query_ids).destroy_all
            end
          end
          true
        end
      end
    end
  end
end

app/controllers/blazer/uploads_controller.rb
module Blazer
  class UploadsController < BaseController
    before_action :ensure_uploads
    before_action :set_upload, only: [:show, :edit, :update, :destroy]

    def index
      @uploads = Blazer::Upload.order(:table)
    end

    def new
      @upload = Blazer::Upload.new
    end

    def create
      @upload = Blazer::Upload.new(upload_params)
      # use creator_id instead of creator
      # since we setup association without checking if column exists
      @upload.creator = blazer_user if @upload.respond_to?(:creator_id=) && blazer_user

      success = params.require(:upload).key?(:file)
      if success
        Blazer::Upload.transaction do
          success = @upload.save
          if success
            begin
              update_file(@upload)
            rescue CSV::MalformedCSVError, Blazer::UploadError => e
              @upload.errors.add(:base, e.message)
              success = false
              raise ActiveRecord::Rollback
            end
          end
        end
      else
        @upload.errors.add(:base, "File can't be blank")
      end

      if success
        redirect_to upload_path(@upload)
      else
        render_errors @upload
      end
    end

    def show
      redirect_to new_query_path(upload_id: @upload.id)
    end

    def edit
    end

    def update
      original_table = @upload.table
      @upload.assign_attributes(upload_params)

      success = nil
      Blazer::Upload.transaction do
        success = @upload.save
        if success
          if params.require(:upload).key?(:file)
            begin
              update_file(@upload, drop: original_table)
            rescue CSV::MalformedCSVError, Blazer::UploadError => e
              @upload.errors.add(:base, e.message)
              success = false
              raise ActiveRecord::Rollback
            end
          elsif @upload.table != original_table
            Blazer.uploads_connection.execute("ALTER TABLE #{Blazer.uploads_table_name(original_table)} RENAME TO #{Blazer.uploads_connection.quote_table_name(@upload.table)}")
          end
        end
      end

      if success
        redirect_to upload_path(@upload)
      else
        render_errors @upload
      end
    end

    def destroy
      Blazer.uploads_connection.execute("DROP TABLE IF EXISTS #{@upload.table_name}")
      @upload.destroy
      redirect_to uploads_path
    end

    private

    def update_file(upload, drop: nil)
      file = params.require(:upload).fetch(:file)
      raise Blazer::UploadError, "File is not a CSV" if file.content_type != "text/csv"
      raise Blazer::UploadError, "File is too large (maximum is 100MB)" if file.size > 100.megabytes

      contents = file.read
      rows = CSV.parse(contents, converters: %i[numeric date date_time])

      # friendly column names
      columns = rows.shift.map { |v| v.to_s.encode("UTF-8").gsub("%", " pct ").parameterize.gsub("-", "_") }
      duplicate_column = columns.find { |c| columns.count(c) > 1 }
      raise Blazer::UploadError, "Duplicate column name: #{duplicate_column}" if duplicate_column

      column_types =
        columns.size.times.map do |i|
          values = rows.map { |r| r[i] }.uniq.compact
          if values.all? { |v| v.is_a?(Integer) && v >= -9223372036854775808 && v <= 9223372036854775807 }
            "bigint"
          elsif values.all? { |v| v.is_a?(Numeric) }
            "decimal"
          elsif values.all? { |v| v.is_a?(DateTime) }
            "timestamptz"
          elsif values.all? { |v| v.is_a?(Date) }
            "date"
          else
            "text"
          end
        end

      begin
        # maybe SET LOCAL statement_timeout = '30s'
        # maybe regenerate CSV in Ruby to ensure consistent parsing
        Blazer.uploads_connection.transaction do
          Blazer.uploads_connection.execute("DROP TABLE IF EXISTS #{Blazer.uploads_table_name(drop)}") if drop
          Blazer.uploads_connection.execute("CREATE TABLE #{upload.table_name} (#{columns.map.with_index { |c, i| "#{Blazer.uploads_connection.quote_column_name(c)} #{column_types[i]}" }.join(", ")})")
          Blazer.uploads_connection.raw_connection.copy_data("COPY #{upload.table_name} FROM STDIN CSV HEADER") do
            Blazer.uploads_connection.raw_connection.put_copy_data(contents)
          end
        end
      rescue ActiveRecord::StatementInvalid => e
        raise Blazer::UploadError, "Table already exists" if e.message.include?("PG::DuplicateTable")
        raise e
      end
    end

    def upload_params
      params.require(:upload).except(:file).permit(:table, :description)
    end

    def set_upload
      @upload = Blazer::Upload.find(params[:id])
    end

    # routes aren't added, but also check here
    def ensure_uploads
      render plain: "Uploads not enabled" unless Blazer.uploads?
    end
  end
end

app/helpers/blazer/base_helper.rb
module Blazer
  module BaseHelper
    def blazer_title(title = nil)
      if title
        content_for(:title) { title }
      else
        content_for?(:title) ? content_for(:title) : nil
      end
    end

    BLAZER_URL_REGEX = /\Ahttps?:\/\/[\S]+\z/
    BLAZER_IMAGE_EXT = %w[png jpg jpeg gif]

    def blazer_format_value(key, value)
      if value.is_a?(Numeric) && !key.to_s.end_with?("id") && !key.to_s.start_with?("id")
        number_with_delimiter(value)
      elsif value.is_a?(String) && value =~ BLAZER_URL_REGEX
        # see if image or link
        if Blazer.images && (key.include?("image") || BLAZER_IMAGE_EXT.include?(value.split(".").last.split("?").first.try(:downcase)))
          link_to value, target: "_blank" do
            image_tag value, referrerpolicy: "no-referrer"
          end
        else
          link_to value, value, target: "_blank"
        end
      else
        value
      end
    end

    def blazer_js_var(name, value)
      "var #{name} = #{json_escape(value.to_json(root: false))};".html_safe
    end

    def blazer_series_name(k)
      k.nil? ? "null" : k.to_s
    end
  end
end

app/views/blazer/queries/_caching.html.erb
<% if @cached_at || @just_cached %>
  <p class="text-muted" style="float: right;">
    <% if @cached_at %>
      Cached <%= time_ago_in_words(@cached_at, include_seconds: true) %> ago
    <% elsif params[:query_id] %>
      Cached just now
      <% if @data_source.cache_mode == "slow" %>
        (over <%= "%g" % @data_source.cache_slow_threshold %>s)
      <% end %>
    <% end %>

    <% if @query && params[:query_id] %>
      <%= link_to "Refresh", refresh_query_path(@query, params: variable_params(@query, @var_params)), method: :post %>
    <% end %>
  </p>
<% end %>

app/views/blazer/queries/_cohorts.html.erb
<% unless @only_chart %>
  <%= render partial: "caching" %>
  <p class="text-muted" style="margin-bottom: 10px;">
    <%= pluralize(@rows.size, "cohort") %>
  </p>
<% end %>
<% if @rows.any? %>
  <div class="results-container">
    <table class="table results-table">
      <thead>
        <tr>
          <th style="min-width: 100px;">Cohort</th>
          <% 12.times do |i| %>
            <th style="width: 7.5%; text-align: right;"><%= @conversion_period.titleize %> <%= i + 1 %></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @rows.each do |row| %>
          <tr>
            <td>
              <%= row[0] %>
              <div style="font-size: 12px; color: #999;"><%= row[1] == 1 ? "1 user" : "#{number_with_delimiter(row[1])} users" %></div>
            </td>
            <% 12.times do |i| %>
              <td style="text-align: right;">
                <% num = row[i + 2] %>
                <% if num %>
                  <% denom = row[1] %>
                  <% if denom > 0 %>
                    <%= (100.0 * num / denom).round %>%
                  <% else %>
                    -
                  <% end %>
                  <div style="font-size: 12px; color: #999;"><%= number_with_delimiter(num) %></div>
                <% else %>
                  -
                <% end %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% elsif @only_chart %>
  <p class="text-muted">No cohorts</p>
<% end %>

app/views/blazer/queries/edit.html.erb
<% blazer_title "Edit - #{@query.name}" %>
<%= render partial: "form" %>

app/views/blazer/queries/home.html.erb
<div id="queries">
  <div id="header">
    <div class="pull-right" style="line-height: 34px;">
      <% if blazer_user %>
        <%= link_to "All", root_path, class: !params[:filter] ? "active" : nil, style: "margin-right: 40px;" %>

        <% if Blazer.audit %>
          <%= link_to "Viewed", root_path(filter: "viewed"), class: params[:filter] == "viewed" ? "active" : nil, style: "margin-right: 40px;" %>
        <% end %>

        <%= link_to "Mine", root_path(filter: "mine"), class: params[:filter] == "mine" ? "active" : nil, style: "margin-right: 40px;" %>
      <% end %>

      <div class="btn-group">
        <%= link_to "New Query", new_query_path, class: "btn btn-info" %>
        <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="caret"></span>
          <span class="sr-only">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu">
          <li><%= link_to "Checks", checks_path %></li>
          <% if Blazer.uploads? %>
            <li><%= link_to "Uploads", uploads_path %></li>
          <% end %>
          <li role="separator" class="divider"></li>
          <li><%= link_to "New Dashboard", new_dashboard_path %></li>
          <li><%= link_to "New Check", new_check_path %></li>
        </ul>
      </div>
    </div>
    <input type="text" v-model="searchTerm" placeholder="Start typing a query, dashboard, or person" style="width: 300px; display: inline-block;" v-focus class="search form-control" />
  </div>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <% if Blazer.user_class %>
          <th style="width: 20%; text-align: right;">Mastermind</th>
        <% end%>
      </tr>
    </thead>
    <tbody class="list" v-cloak>
      <tr v-for="query in visibleItems">
        <td>
          <a :href="itemPath(query)" :class="{ dashboard: query.dashboard }">{{ query.name }}</a>
          <span class="vars">{{ query.vars }}</span>
        </td>
        <% if Blazer.user_class %>
          <td class="creator">{{ query.creator }}</td>
        <% end %>
      </tr>
    </tbody>
  </table>

  <p v-if="more" class="text-muted">Loading...</p>
</div>

<script>
  <%= blazer_js_var "dashboards", @dashboards %>
  <%= blazer_js_var "queries", @queries %>
  <%= blazer_js_var "more", @more %>

  var prepareSearch = function (list) {
    var i, q, searchStr
    for (i = 0; i < list.length; i++) {
      q = list[i]
      searchStr = q.name + q.creator
      if (q.creator === "You") {
        searchStr += "mine me"
      }
      q.searchStr = prepareQuery(searchStr)
    }
  }

  var prepareQuery = function (str) {
    return str.toLowerCase()
  }

  var app = Vue.createApp({
    data: function() {
      return {
        searchTerm: "",
        more: more,
        updateCounter: 0
      }
    },
    created: function() {
      this.listItems = dashboards.concat(queries)

      prepareSearch(this.listItems)

      this.queryIds = {}
      for (i = 0; i < queries.length; i++) {
        this.queryIds[queries[i].id] = true
      }

      if (this.more) {
        var _this = this

        $.getJSON(Routes.queries_path(), function (data) {
          var i, j, newValues, val, size = 500;

          var newValues = []
          for (j = 0; j < data.length; j++) {
            val = data[j]
            if (val && !_this.queryIds[val.id]) {
              newValues.push(val)
            }
          }

          prepareSearch(newValues)

          _this.listItems = _this.listItems.concat(newValues)
          _this.more = false
          // hack to get to update
          _this.updateCounter++
        })
      }
    },
    computed: {
      visibleItems: function () {
        // hack to get to update
        this.updateCounter

        var pageSize = 200
        var q, i

        if (this.searchTerm.length > 0) {
          var term = prepareQuery(this.searchTerm)
          var items = []
          var fuzzyItems = []
          for (i = 0; i < this.listItems.length; i++) {
            q = this.listItems[i]
            if (q.searchStr.indexOf(term) !== -1) {
              items.push(q)
              if (items.length == pageSize) {
                break
              }
            } else if (fuzzysearch(term, q.searchStr)) {
              fuzzyItems.push(q)
            }
          }
          return items.concat(fuzzyItems).slice(0, pageSize)
        } else {
          return this.listItems.slice(0, pageSize)
        }
      }
    },
    methods: {
      itemPath: function (item) {
        if (item.dashboard) {
          return Routes.dashboard_path(item.to_param)
        } else {
          return Routes.query_path(item.to_param)
        }
      }
    },
    directives: {
      focus: {
        inserted: function (el) {
          el.focus()
        }
      }
    }
  })
  app.config.compilerOptions.whitespace = "preserve"
  app.mount("#queries")
</script>

app/views/blazer/queries/new.html.erb
<% blazer_title "New Query" %>
<%= render partial: "form" %>

app/views/blazer/queries/show.html.erb
<% blazer_title @query.name %>

<% if @success %>
  <% run_data = {statement: @query.statement, query_id: @query.id, data_source: @query.data_source, variables: variable_params(@query)} %>
  <% run_data.merge!(forecast: "t") if params[:forecast] %>
  <% run_data.merge!(cohort_period: params[:cohort_period]) if params[:cohort_period] %>
<% end %>

<div class="topbar">
  <div class="container">
    <div class="row" style="padding-top: 13px;">
      <div class="col-sm-9">
        <%= render partial: "blazer/nav" %>
        <h3 style="line-height: 34px; display: inline; margin-left: 5px;">
          <%= @query.name %>
        </h3>
      </div>
      <div class="col-sm-3 text-right">
        <%= link_to "Edit", edit_query_path(@query, params: variable_params(@query)), class: "btn btn-default", disabled: !@query.editable?(blazer_user) %>
        <%= link_to "Fork", new_query_path(params: {variables: variable_params(@query), fork_query_id: @query.id, data_source: @query.data_source, name: @query.name}), class: "btn btn-info" %>

        <% if !@error && @success %>
          <%= button_to "Download", run_queries_path(format: "csv"), params: run_data, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div style="margin-bottom: 60px;"></div>

<% if @sql_errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @sql_errors.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if @query.description.present? %>
  <p><%= @query.description %></p>
<% end %>

<%= render partial: "blazer/variables", locals: {action: query_path(@query)} %>

<pre id="code"><code><%= @statement.display_statement %></code></pre>

<% if @success %>
  <div id="results">
    <p class="text-muted">Loading...</p>
  </div>

  <script>
    function showRun(data) {
      $("#results").html(data)
      $("#results table").stupidtable(stupidtableCustomSettings).stickyTableHeaders({fixedOffset: 60})
    }

    function showError(message) {
      $("#results").addClass("query-error").html(message)
    }

    <%= blazer_js_var "data", run_data %>

    runQuery(data, showRun, showError)
  </script>
<% end %>

<% unless %w(mongodb).include?(Blazer.data_sources[@query.data_source].adapter) %>
  <script>
    // do not highlight really long queries
    // this can lead to performance issues
    var code = $("#code code")
    if (code.text().length < 10000) {
      hljs.highlightElement(code.get(0))
    }
  </script>
<% end %>